[package]
name = "rust_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5"
gnuplot = "0.0.39"
plotters = "0.3.5" 
